default: &default
  adapter: redis
  url: redis://localhost:6379

development:
  <<: *default
  channel_prefix: campfire_development

test:
  adapter: test

performance:
  <<: *default
  channel_prefix: campfire_performance

production:
  <<: *default
  url: redis://redis:6379
  channel_prefix: campfire_production
